# Generated by Django 5.0.6 on 2024-07-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('classroom_period', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomperiod',
            name='class_room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_periods', to='classes.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroomperiod',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_periods', to='courses.courses'),
            preserve_default=False,
        ),
    ]
