# Generated by Django 5.0.6 on 2024-07-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.SmallIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('course_description', models.TextField()),
                ('class_starting_time', models.TimeField(auto_now=0, verbose_name=0)),
                ('course_trainer_name', models.CharField(max_length=100)),
                ('number_of_students', models.PositiveSmallIntegerField()),
                ('grade_level', models.PositiveSmallIntegerField()),
                ('school_term', models.IntegerField()),
                ('assement_requirements', models.TextField()),
                ('course_students', models.ManyToManyField(related_name='courses', to='student.student')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teacher.teacher')),
            ],
        ),
    ]
